### ISSUE TITLE
请问怎么启动该项目，非常感谢

### ISSUE THREAD

**Issue by ShenGunNiTian** [Hxiaodou/heiyaMusic#2]

**Comment by huangshihai** [comment]
用的是springboot框架，JDK1.8版本，直接启动MusicApplication就好了

**Comment by ShenGunNiTian** [comment]
谢谢，后面能运行访问成功了，以为是直接启动tomcat的，没想到要启动那个类。还有想问一下，想在播放条那加上歌名和歌手以及时间，不知道应该怎么做。还有，方便留一下邮箱吗？非常感谢

**Comment by Hxiaodou** [comment]
942212756@qq.com
